CODIFICAÇÃO/app/controllers/auth_controller.py
from flask import Blueprint, render_template, redirect, url_for, flash, session
from app.forms import SignupForm, LoginForm
from app.models.user import User
from app import db
from app.models.user import get_emblema_url
bp = Blueprint("auth", __name__, url_prefix="/auth")


@bp.route("/signup", methods=["GET", "POST"])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("Cadastrado, agora voce pode entrar para o Clã!")
        return redirect(url_for("auth.login"))
    return render_template("auth/signup.html", title="Sign Up", form=form)


@bp.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash("Invalid username or password")
            return redirect(url_for("auth.login"))
        
        emblema_url = get_emblema_url(user.pontos)
        session["username"] = form.username.data
        session["emblema_url"] = emblema_url
        return redirect(url_for("main.principal"))
    return render_template("auth/login.html", title="Sign In", form=form)


@bp.route("/logout")
def logout():
    session.pop("username", None)
    return redirect(
        url_for("main.index")
    )  # Redireciona para a rota principal após o logout

CODIFICAÇÃO/app/controllers/main_controller.py
from flask import Blueprint, render_template, redirect, url_for, flash,session
from app.forms import SignupForm, LoginForm
from functools import wraps

bp = Blueprint('main', __name__,template_folder='templates/main')

def verificar_autenticacao(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'username' not in session or session.get('username') is None:
            flash('Você precisa fazer login para acessar esta página.', 'warning')
            return redirect(url_for('auth.login'))
        return f(*args, **kwargs)
    return decorated_function

@bp.route('/')
def index():
    return render_template('index.html')

@bp.route('/principal')
@verificar_autenticacao
def principal():
        return render_template('main/principal.html')
    
    
@bp.route('/usuario')
@verificar_autenticacao
def usuario():  
        return render_template('main/usuario.html')
   

@bp.route('/rank')
@verificar_autenticacao
def rank():
        return render_template('main/rank.html')
    

CODIFICAÇÃO/app/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/icons/favicon.ico') }}" />
    <!--===============================================================================================-->

    <link rel="stylesheet" type="text/css"
        href="{{ url_for('static', filename='fonts/font-awesome-4.7.0/css/font-awesome.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/animate/animate.css') }}">
    <link rel="stylesheet" type="text/css"
        href="{{ url_for('static', filename='vendor/css-hamburgers/hamburgers.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/select2/select2.min.css') }}">
    <!-- <link href="{{ url_for('static', filename='/css/bootstrap.css') }}" rel="stylesheet"> -->


    <!--===============================================================================================-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/util.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='/css/meu.css') }}">

    <title>Hackers School</title>
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <div class=""></div>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="nav navbar-nav">
                <img class="imgLogo" src="{{ url_for('static', filename='images/icons/icone1.png')}}" alt="logo">
            </div>

            <div class="navbar-nav logotipo">
                <a class="navbar-brand" href="#">Hackers School</a>

            </div>

            <ul class="nav navbar-nav">
                <li class="active"><a class="nav-link active text-white btn btn-secondary btn-lg"
                        href="{{ url_for('main.index') }}">Home</a>
                </li>
                <li><a class="nav-link active text-white btn btn-secondary btn-lg"
                        href="{{ url_for('auth.login') }}">Login</a></li>
                <li> <a class="nav-link text-white btn btn-secondary btn-lg"
                        href="{{ url_for('auth.signup') }}">Cadastro</a></li>
                <li><a class="nav-link text-white btn btn-secondary btn-lg"
                        href="{{ url_for('main.usuario') }}">Perfil</a></li>
                <li> <a class="nav-link text-white btn btn-secondary btn-lg" href="{{ url_for('main.rank') }}">Rank</a>
                </li>
                <li><a class="nav-link text-white btn btn-secondary btn-lg"
                        href="{{ url_for('main.principal') }}">Quiz</a>
                </li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if 'username' in session %}
                    <li>
                        <a href="{{ url_for('main.rank') }}">
                            <span class="btn">
                                <img class="imgRank" src="{{ session['emblema_url'] }}" alt="Emblema do usuário">
                            </span>
                            <span>Usuário: {{ session['username'] }}</span>
                        </a>
                    </li>
                {% endif %}
                <li>
                    <a class="nav-link text-white btn" href="{{ url_for('auth.logout') }}">
                        <span class="glyphicon glyphicon-log-in"></span> Sair
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="entrarMensagens text-center">
        {% with messages = get_flashed_messages() %}
        <!-- {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %} -->
        {% endwith %}
        {% block content %}
        {% endblock %}
    </div>



    <script src="{{ url_for('static', filename='vendor/jquery/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/popper.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/select2/select2.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/tilt/tilt.jquery.min.js') }}"></script>
    <!-- <script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script> -->

    <script>
        $('.js-tilt').tilt({
            scale: 1.1
        })
    </script>
    <!--===============================================================================================-->
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>

</html>

CODIFICAÇÃO/app/templates/index.html
<!-- app/templates/main/index.html -->

{% extends 'base.html' %}

{% block title %}Página Inicial{% endblock %}

{% block content %}
<h1 class="text-center mt-5 mb-5 bold">Bem-vindo à Hackers School!</h1>

<div class="sombraBox">
    <img src="{{ url_for('static', filename='images/hackers2.gif') }}" class="logoHome" alt="Logo">
</div>
<!-- Adicione mais conteúdo aqui, se necessário -->
{% endblock %}